# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chHo1Oj7HSRjcXsnGJIl_ARaSdNXwmkg
"""

import streamlit as st
import requests

st.set_page_config(
    page_title="Agentic AI PDF QA",
    layout="centered"
)

st.title("📄 Agentic AI PDF Query Answering System")

question = st.text_input(
    "Ask a question from the PDF"
)

if st.button("Get Answer"):

    response = requests.post(
        "http://127.0.0.1:8000/ask",
        json={
            "question": question
        }
    )

    result = response.json()

    st.subheader("Answer")
    st.write(result["answer"])