# -*- coding: utf-8 -*-
"""agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chHo1Oj7HSRjcXsnGJIl_ARaSdNXwmkg
"""

from langchain.agents import initialize_agent
from langchain.agents import Tool
from langchain.chat_models import ChatOpenAI

from rag_pipeline import get_answer

llm = ChatOpenAI(
    temperature=0
)

def pdf_query_tool(query):
    return get_answer(query)

pdf_tool = Tool(
    name="PDF Question Answering Tool",
    func=pdf_query_tool,
    description="Answers questions from PDF documents"
)

agent = initialize_agent(
    tools=[pdf_tool],
    llm=llm,
    agent="zero-shot-react-description",
    verbose=True
)

def ask_agent(question):
    response = agent.run(question)
    return response