# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from fastapi import FastAPI
from pydantic import BaseModel
from rag_pipeline import get_answer

app = FastAPI()


class QueryRequest(BaseModel):
    question: str


@app.get("/")
def home():
    return {
        "message": "Agentic AI PDF Query Answering System Running"
    }


@app.post("/ask")
def ask_question(request: QueryRequest):

    response = get_answer(request.question)

    return {
        "question": request.question,
        "answer": response
    }