# -*- coding: utf-8 -*-
"""rag_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chHo1Oj7HSRjcXsnGJIl_ARaSdNXwmkg
"""

import os
from dotenv import load_dotenv

from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import FAISS

from langchain.chat_models import ChatOpenAI
from langchain.chains.question_answering import load_qa_chain

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

loader = PyPDFLoader("../data/sample.pdf")

documents = loader.load()

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

texts = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings(
    openai_api_key=OPENAI_API_KEY
)

vectorstore = FAISS.from_documents(
    texts,
    embeddings
)

llm = ChatOpenAI(
    temperature=0,
    openai_api_key=OPENAI_API_KEY
)

qa_chain = load_qa_chain(
    llm,
    chain_type="stuff"
)

def get_answer(question):

    docs = vectorstore.similarity_search(
        question,
        k=4
    )

    response = qa_chain.run(
        input_documents=docs,
        question=question
    )

    return response